name: psci
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.*
    - matplotlib=3.*
    - pandas=0.24.*
    - jupyter
    - seaborn=0.8.1
    - xlrd=1.1.0
    - pyarrow
    - joblib
    - scikit-learn=0.20.*
    - openpyxl=2.5.1
    - requests
    - lxml
